### ISSUE TITLE
Suggested Updates for RSB Version 0 format.

### ISSUE THREAD

**Issue by boristsr** [AlexKimov/RSE-file-formats#1]
Hi,
Thanks for putting this information up. It's incredibly useful for a hobby project I'm working through.

I've discovered some information that may be useful for you, and that could be added to the wiki.

Version 0 files store a palette, as you know. The palette order is BGRA, not RGBA. The 16 bit version of the image stored at the end of the file, remains RGB. Although the palette seems to have a valid alpha field, the alpha value for most images is 0 on all pixels. I found that I was better off just discarding the alpha field and replacing it with 255 for my extracted images.

The template for 010 Editor, the Pixel Array 24 field, has the wrong labels for the fields. It's saying the fields are Alpha, Red, Green, when it should read Red, Green, Blue.

You have a boolean at the top of the bt template file to specify if it's a "type1" file or not. This just specifies whether the file has a palette and 256 color image stored in addition to the full colour image stored last. You could check the size of the file and determine whether a 256 color image is stored, or another simple check I have used which seems to work is just check if the width and height of the image are power of 2. If they are not power of 2 dimensions, it will not contain a 256 color image. This has been tested on the GOG version of rainbow six, and a few files from a demo version of rogue spear (which uses version 1 format anyway).

I'm not at all familiar with 010 Editor, but if i get time I'll try and submit a pull request with some of these changes.

I'm writing a set of python scripts to convert some of these formats to more open formats, with a particular focus on R6, Eagle Watch, and Rogue Spear. The RSB converter is pretty much complete for version 0 and 1 files, and later formats except it doesn't extract the information after the image data, or process DXT images (although it reads all meta data for them). It could easily be extended to extract the remaining information into a JSON file, but I'll get to that later.

I'll release the scripts under a new repo on my account in the coming weeks, and I'll continue to post issues if I discover any extra information that may help you or others.

Hope this helps. Let me know if I can help out any further.

**Comment by AlexKimov** [comment]
Hi, Phlip. I forgot to upload the lastest version ). How i can find you (email, telegram...)?

**Comment by boristsr** [comment]
Hi Alex, you can reach me at philip@gdcorner.com.

Have you made any progress on SOB formats? I'm working through those files
at the moment, some files process well but some have different material
definitions that I'm beginning to investigate.
